---
title: "Multiple Groups Latent Variable Models"
author: "Andrew L. Stewart"
date: "June 8, 2017"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read the data
```{r}
multigroup.dat <- read.table("./HMK_MGCFA.dat")
names(multigroup.dat)<-c("math1","math2","math3","read1","read2","read3","iq","selfreg","value","gender")
attach(multigroup.dat)
library(lavaan)
library(semPlot)
```

# Specify the model
```{r}
  model <- '
            #Measurement model
            math =~ math1+math2+math3
            read =~ read1+read2+read3
            
            #regressions
            math~iq+selfreg+value
            read~iq+selfreg+value
'
```

#Fit the configural invariance model
```{r}
fit<-cfa(model,meanstructure=TRUE,group="gender",data=multigroup.dat)
summary(fit,fit.measures=TRUE,standardized=TRUE)
semPaths(fit,intercepts = FALSE,whatLabels = "stand",rotation=2)
```

#Fit the metric invariance model
```{r}
fit<-cfa(model,meanstructure=TRUE,group="gender",group.equal=c("loadings"),data=multigroup.dat)
summary(fit,fit.measures=TRUE,standardized=TRUE)
semPaths(fit,intercepts = FALSE,whatLabels = "stand",rotation=2)
```

# Fit the scalar invariance model
```{r}
fit<-cfa(model,meanstructure=TRUE,group="gender",group.equal=c("loadings","intercepts"),data=multigroup.dat)
summary(fit,fit.measures=TRUE,standardized=TRUE)
semPaths(fit,intercepts = FALSE,whatLabels = "stand",rotation=2)
```