---
title: ''
author: ''
date: ''
output:
  pdf_document: default
  html_document: default
  word_document: default
---

# Why are People Biased When Reasoning About the Status Quo?

## Study Description

The ability to reason about cause and effect is a fundamental human trait. Yet, people rarely think about all of the possible causes for a particular effect, and instead rely on heuristic explanations that seem plausible. Such biases may be present for how individuals explain the status quo. When people think about why something “is,” they may assume that there is an inherent property of the thing that causes it to be so. For example, imagine Susan is thinking about why she is best friends with Allison. Susan may believe that she and Allison are “meant” to be friends because they have inherent traits (e.g., similar senses of humor) that lead them to be compatible. Susan may believe this cause to be a plausible explanation for her friendship with Allison, even though another reason that they are friends is that they were randomly assigned to be suitemates during their freshman year at college.

People’s tendency to confuse what ‘is’ with what ‘ought to be’ is the focus of research by Tworek and Cimpian (2016). These researchers wanted to determine whether individuals tendency to explain events based on their inherent properties (i.e., inherence bias) would predict the extent to which they view typical outcomes as good and desirable.

To study this, the researchers recruited 122 individuals from an online participant pool. The participants first read six articles that explained a status quo societal practice (e.g., Americans eat a lot of pizza). After reading each article, participants responded to various questions assessing the extent to which the status quo ought to occur (e.g., Americans eat a lot of pizza because pizza is delicious). These questions measured participants tendency to make Ought inferences. Next, participants responded to 15 items designed to measure their level of inherence bias (i.e., their tendency to explain events based on inherent properties). Participants also completed various additional measures, including a measure of intelligence (Raven’s Progressive Matrix), belief in a just world, political views (Conservatism), and demographics (education). For more details, see the Tworek and Cimpian (2016) Study 1 method section.

## Analyses

1. Open the data file (called Tworek and Cimpian Study 1). Explore the data file. Note, you will not analyze all of these variables. Try to find the variables that are relevant to the study description above.

2. This data file includes some participants who were excluded from the data analysis because they live outside the United States, or because they failed an attention check. Using the SELECT CASES function, use the filter variable filter_$ (labeled Excluded = 0). Check the data file to ensure that excluded participants are not selected for analysis.

3. Perform an analysis to determine whether people’s inherence bias is associated with their tendency to believe the status quo ought to be (Ought_Score). Estimate both the correlation and the regression line.

4. Now, you want to show that this relationship is robust. In other words, the relationship between a person’s inherence bias and their ought exists after controlling for many other factors. Perform a partial correlation analysis between ought_score and inherence bias, controlling for education level, Raven’s Progressive matrix score, conservatism, and belief in a just world. Interpret the results and compare them to the zero order correlation.

5. Prepare an APA-style results section to describe each of the analyses conducted above.

## DUE: April 21, 2017 at 3PM
### Upload your APA style results section and any requested tables/figures, along with your output in one file to Moodle.