---
title: ""
author: ""
date: ""
output: pdf_document
---

# Do spoken or written words better express intelligence?

## Study Description

Imagine you were a job candidate trying to pitch your skills to a potential employer. Would you be more likely to get the job after giving a short speech describing your skills, or after writing a short speech and having a potential employer read those words? That was the question raised by Schroeder and Epley (2015). The authors predicted that a person’s speech (i.e., vocal tone, cadence, and pitch) communicates information about their intellect better than their written words (even if they are the same words as in the speech).

To examine this possibility, the authors randomly assigned 39 professional recruiters for Fortune 500 companies to one of two conditions. In the audio condition, participants listened to audio recordings of a job candidate’s spoken job pitch. In the transcript condition, participants read a transcription of the job candidate’s pitch. After hearing or reading the pitch, the participants rated the job candidates on three dimensions: intelligence, competence, and thoughtfulness. These ratings were then averaged to create a single measure of the job candidate’s intellect, with higher scores indicating the recruiters rated the candidates as higher in intellect. The participants also rated their overall impression of the job candidate (a composite of two items measuring positive and negative impressions). Finally, the participants indicated how likely they would be to recommend hiring the job candidate (0 - not at all likely, 10 -extremely likely).

## Analyses

1. Open the data file (called Schroeder and Epley 2015 Experiment 4 data). Explore the data file. Note, you will not analyze all of these variables. Try to find the variables that are relevant to the study description above.

2. You first want compare participants in the audio condition to participants in the transcript condition on the Intellect_Rating variable. Which type of analysis is appropriate, given the design described above?

3. Next compare participants in the audio condition to participants in the transcript condition on the Impression_Rating variable.

4. Finally, compare participants in the audio condition to participants in the transcript condition on the Hire_Rating variable

5. Prepare an APA-style results paragraph describing the results of the analyses performed above.

6. Generate a figure to depict the results of the analyses performed above. Make sure to follow APA guidelines, and include error bars representing +/- 1 standard error of the mean.

## DUE: March 17, 2017 at 3PM
### Upload your APA style results section and any requested tables/figures, along with your output in one file to Moodle.