---
title: ""
author: ""
date: ""
output: pdf_document
---

# Does Music Convey Social Information to Infants? (Part 1)

## Study Description

Parents often sing to their children and, even as infants, children listen to and look at their parents while they are singing. Research by Mehr, Song, and Spelke (2016) sought to explore the psychological function that music has for parents and infants, by examining the hypothesis that particular melodies convey important social information to infants. Specifically, melodies convey information about social affiliation.

The authors argue that melodies are shared within social groups. Whereas children growing up in one culture may be exposed to certain songs as infants (e.g., “Rock-a-bye Baby”), children growing up in other cultures (or even other groups within a culture) may be exposed to different songs. Thus, when a novel person (someone who the infant has never seen before) sings a familiar song, it may signal to the infant that this new person is a member of their social group.

To test this hypothesis, the researchers recruited 32 infants and their parents to complete an experiment. During their first visit to the lab, the parents were taught a new lullaby (one that neither they nor their infants had heard before). The experimenters asked the parents to sing the new lullaby to their child every day for the next 1-2 weeks.

Following this 1-2 week exposure period, the parents and their infant returned to the lab to complete the experimental portion of the study. Infants were first shown a screen with side-by-side videos of two unfamiliar people, each of whom were silently smiling and looking at the infant. The researchers recorded the looking behavior (or gaze) of the infants during this ‘baseline’ phase. Next, one by one, the two unfamiliar people on the screen sang either the lullaby that the parents learned or a different lullaby (that had the same lyrics and rhythm, but a different melody). Finally, the infants saw the same silent video used at baseline, and the researchers again recorded the looking behavior of the infants during this ‘test’ phase.

## Analyses

1. Open the data file (called Mehr Song and Spelke Experiment 1). Explore the data file. Note, you will not analyze all of these variables. Try to find the variables that are relevant to the study description above.

2. This data file includes the variables for all 5 experiments reported in the paper. We only want to analyze the data for Experiment 1. Using the SELECT CASES function, use the filter variable filter_$ (labeled Experiment 1 ONLY). Check the data file to ensure that only cases 1-32 are selected for analysis.

3. You first want to show that infants’ looking behavior did not differ from chance during the baseline trial. In other words, the infants did not show an attentional bias prior to hearing the unfamiliar others sign the song. Perform a one-sample t-test to examine whether the proportion of time spent looking at the person singing the familiar song at baseline did not differ from chance (0.5).

4. Now, perform a one-sample t-test to examine whether the proportion of infants’ looking behavior toward the singer of the familiar melody was higher than chance at the test phase (0.5).

5. Prepare an APA-style results section to describe each of the analyses conducted above.

6. Generate a scatterplot to depict the relationship between the estimated number of times the infants heard the song and their increased looking behavior from the baseline to test trials.

## DUE: FEBRUARY 24, 2017 at 3PM
### Upload your APA style results section and any requested tables/figures, along with your output in one file to Moodle.