---
title: ""
author: ""
date: ""
output: pdf_document
---

# Does Sharing a Painful Experience with Other People Lead to More Trusting Relationships?

## Study Description

Great friendships are often forged in the fires of difficult and even traumatic experiences. Hazing rituals, for example, entail individuals undergoing embarrassing and sometimes painful initiations, yet often lead to increased bonding among those individuals. A study by Bastian, Jetten, and Ferris (2014) sought to examine the effects of shared painful experiences on cooperation and trust.

To study this, the authors randomly assigned participants to either a pain condition or a control condition, with participants in both conditions completing the study in small groups. Participants in the pain condition completed two tasks designed to induce pain: a cold-pressor task (submerging their hands into ice water for as long as possible, up to 90 seconds), and then a wall squat (leaning against a wall with legs bent at a 90 degree angle). Participants in the control condition also completed tasks (e.g., locating metal balls at the bottom of a container) that were designed to be purposeful, but not painful.

After the pain induction, participants completed a measure of positive and negative affect, a measure of challenge and threat response, and the primary dependent variable, which was a seven-item scale designed to measure their level of bonding with the other participants. Finally, participants completed two manipulation checks, assessing the intensity and unpleasantness of the tasks they completed earlier.

## Analyses

1. Open the data file (called Bastian Jetten and Ferris Experiment 1). Explore the data file. Note, you will not analyze all of these variables. Try to find the variables that are relevant to the study description above.

2. You first run an analysis to test whether the pain manipulation was successful. Conduct a t-test to compare participants in the pain condition vs. the control condition for the pain intensity and pain unpleasantness variables.

3. Next, you want to examine whether the manipulation led to differences in positive and negative affect between the conditions. Perform t-tests to explore this possibility.

4. You also want to examine whether the manipulation was more threatening or challenging for the pain condition compared to the control condition. Perform a t-test to explore this possibility.

5. Finally, to test the main prediction, conduct a one-way ANOVA to determine whether the manipulation led to a difference in group bonding. To conduct this test, you will first need to compute a new variable that reflects the mean of the seven items used to measure bonding (group101, group102, group103, group104, group105, group106, group107). Name your new variable BONDING_MEAN. Then perform a one-way ANOVA with CONDITION as the independent variable and BONDING_MEAN as the dependent variable.

6. Prepare an APA-style results section to describe each of the analyses conducted above.

7. Generate a bar graph to depict the results. Don’t forget to include error bars that reflect the 95% confidence intervals.

## DUE: March 24, 2017 at 3PM
### Upload your APA style results section and any requested tables/figures, along with your output in one file to Moodle.